### ISSUE TITLE
feature request: use the global Promise instead of bluebird

### ISSUE THREAD

**Issue by forivall** [joeattardi/promise-poller#14]
It appears that the main bluebird feature you're using is `timeout`. In general, it's nice to not force a bluebird dependency.

**Comment by joeattardi** [comment]
I just released 1.8.0 which removes the Bluebird dependency, and instead uses the global `Promise`. Please feel free to file another issue if you run into problems with the new release.

**Comment by forivall** [comment]
Thanks! I wasn't expecting the quick turn around since you seemed a little absent 😅 . Through using the poller in a somewhat novel setup, I found 2 new issues, and filed them at #15 and #16. 

Also, [I created typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38508), (but they're missing the new `CANCEL_TOKEN`, since you just added that 😄 ).

Thanks for your work!
