### ISSUE TITLE
Short circuit on certain exception types

### ISSUE THREAD

**Issue by joeattardi** [joeattardi/promise-poller#2]
Some exceptions may be due to a condition that won't change over the course of polling - for example, a syntax error.

The idea would be, if we fail on one of these types of exceptions, to stop polling early since we won't have any different results.

**Comment by jwesly** [comment]
Was this ever implemented?

**Comment by joeattardi** [comment]
No, I never did get around to it. I wasn't sure it was needed, but can always re-open it if there are good use cases for it.

**Comment by jwesly** [comment]
I have an application I might want to reject the master promise early depending on what response I get from a RESTful API, eg if json.response == pending keep polling but if json.response == failed stop polling.

**Comment by joeattardi** [comment]
I've been thinking about doing something like that. Like return false from the task function to just reject the master promise. I'll add that!

**Comment by joeattardi** [comment]
I've added this functionality and released version 1.5.0. To reject the master promise early, just return false from the task function.
