### ISSUE TITLE
Timeout does not work

### ISSUE THREAD

**Issue by Jpunt** [joeattardi/promise-poller#4]
The timeout-functionality seems to be broken:

```js
require('promise-poller')({
  taskFn: () => {
    console.log('polling...');
    return Promise.reject();
  },
  interval: 10,
  timeout: 1000,
})
.then(() => console.log('success'))
.catch(() => console.log('failed'));
```

This will log "polling..." 5 times (which seems to be the default) and then fails. When adding `retries: Infinity`, it keeps polling infinitely.

Any idea what's up?

**Comment by joeattardi** [comment]
You're rejecting the promise immediately (return Promise.reject()$. So your task function runs and completes immediately. 

The timeout comes into play for a task function that will take some time, like an Ajax request or something and if the promise returned by the task function doesn't resolve within 'timeout' milliseconds, it will reject. 

Does that make sense?

**Comment by Jpunt** [comment]
Ah, that's something different than I thought it would be. I saw it as an alternative to `retries`, so it would try something over and over again, until a certain time was passed. Basically, `x / interval` as the amount of `retries`. Which is what I did in the meantime :) Thanks!

**Comment by joeattardi** [comment]
Ok, great. Sorry for the confusion! I'll update the README to be a little clearer.
