### ISSUE TITLE
Add "total poll" timeout

### ISSUE THREAD

**Issue by joeattardi** [joeattardi/promise-poller#5]
Currently, the `timeout` option sets the timeout for *each individual poll*. It might also be handy to have a timeout for the *entire poll operation*.

So, for example:

`timeout: 10000` means "every time you poll, reject the promise for that poll iteration if it's not resolved after 10 seconds.

`totalTimeout: 10000` means "while polling one or more times, reject the master promise if there isn't a successful poll after 10 seconds."

**Comment by Jpunt** [comment]
Nice, this would be what i've been expecting in #4 👍

**Comment by joeattardi** [comment]
Implemented in 1.4.0
