### ISSUE TITLE
Passing arguments to taskFn

### ISSUE THREAD

**Issue by NathanKleekamp** [joeattardi/promise-poller#6]
Apologies if I missed it in the documentation, but is it possible to pass arguments to the taskFn? Thanks for your work on this project!

**Comment by joeattardi** [comment]
There isn't a way to directly pass them, what I usually do is either have the taskFn be a function that calls another function, passing arguments, like this:

    taskFn: function () {
      myOtherFunction(arg1, arg2, arg3);
    }

Or you can use `bind`:

    taskFn: myOtherFunction.bind(this, arg1, arg2, arg3);

If you mean passing *different* arguments to the taskFn each time, there currently isn't a way to do that.

**Comment by NathanKleekamp** [comment]
I realized that I didn't reply early, so just wanted to circle back and say thanks. I went the bind route. Thanks!

**Comment by haganbt** [comment]
This is really helpful; I was hitting this issue.

Thanks for a great module!
