### ISSUE TITLE
masterTimeout value is not taken into account (globalTimeout is used)

### ISSUE THREAD

**Issue by blurab** [joeattardi/promise-poller#7]
I've try a stupid test by setting the masterTimeout value and it seems not taken into account, there is a kind of timeout that occur but not at the time specified in masterTimeout  value
I've look at the code, when masterTimeout  then it create a setTiemout with the field options.globalTimeout:

` if (options.**masterTimeout**) {
      setTimeout(() => reject('master timeout'), options.**globalTimeout**);`

**Comment by blurab** [comment]
now if I set the following value in options:
var poller = promisePoller({
  taskFn: myTask,
//  strategy: 'linear-backoff',
  masterTimeout: 3000,
  globalTimeout: 3000
});
so I set both master & global as a workaround
with the following tastk:
function myTask() {
	return new Promise(function(resolve,reject){
		console.dir('error !');
  		reject('err');
	})
}

here is the console output:
'error !'
'error !'
'error !'
'master timeout'
'error !'
'error !'

the 'master timeout' is fired but it does not cancel the retry !

**Comment by joeattardi** [comment]
Thanks for reporting this. The issue should be fixed now in version 1.5.1.

**Comment by blurab** [comment]
I've run the test and it works like a charm, thanks !
