### ISSUE TITLE
Cannot cancel from within promise

### ISSUE THREAD

**Issue by countergram** [joeattardi/promise-poller#9]
> You may want to cancel the polling early. For example, if the poll fails because of an invalid password, that's not likely to change, so it would be a waste of time to continue to poll. To cancel polling early, return false from the task function instead of a promise.

The use cases I have had so far for polling all involve async tasks, which cannot cancel the polling operation if they encounter an error that should be fatal, because they can't make the task function return false instead of a promise.

One possibility would be to add a unique sentinel value/error type for cancelation.

A possible workaround is to maintain a flag in the enclosing scope that allows cancellation on the *next* invocation, but this isn't as nice as canceling immediately especially if the interval is high.

**Comment by joeattardi** [comment]
Hi, sorry it took me over 2 and a half years to address this, but I think I've added a solution to this problem. Basically, the library exports a special `CANCEL_TOKEN`. If you want to cancel polling, you can return a promise that rejects with this token. I think this should have the desired effect.

I've just released 1.9.0 which has this new feature.
